services:
  app:
    build: .
    command: ["serve", "--db-path=/app/data.db", "--listen-addr=:8090"]
    ports:
      - "8090:8090"
    volumes:
      - app-data:/app
    working_dir: /app

  cleanup:
    build: .
    command: ["cleanup", "--db-path=/app/data.db"]
    volumes:
      - app-data:/app
    working_dir: /app
    profiles:
      - cleanup

  block:
    build: .
    entrypoint: ["image-uploader", "block", "--db-path=/app/data.db"]
    volumes:
      - app-data:/app
    working_dir: /app
    profiles:
      - block

  unblock:
    build: .
    entrypoint: ["image-uploader", "unblock", "--db-path=/app/data.db"]
    volumes:
      - app-data:/app
    working_dir: /app
    profiles:
      - unblock

volumes:
  app-data:
